In [35]:
from tensorflow.keras.preprocessing.text import one_hot


In [36]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [37]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [38]:
#defining the vocabulary size
voc_size = 10000

In [39]:
#one hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [40]:
one_hot_repr

[[2608, 7686, 7767, 8406],
 [2608, 7686, 7767, 1223],
 [2608, 7740, 7767, 8079],
 [1014, 4189, 3171, 4427, 9610],
 [1014, 4189, 3171, 4427, 9131],
 [1178, 2608, 7278, 7767, 7898],
 [9105, 8072, 4456, 4427]]

##### Word embedding representation


In [41]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input
import numpy as np

In [42]:
max_length = 8

In [43]:
embedded_docs = pad_sequences(sequences=one_hot_repr,maxlen=max_length,padding='post',truncating='post')
embedded_docs

array([[2608, 7686, 7767, 8406,    0,    0,    0,    0],
       [2608, 7686, 7767, 1223,    0,    0,    0,    0],
       [2608, 7740, 7767, 8079,    0,    0,    0,    0],
       [1014, 4189, 3171, 4427, 9610,    0,    0,    0],
       [1014, 4189, 3171, 4427, 9131,    0,    0,    0],
       [1178, 2608, 7278, 7767, 7898,    0,    0,    0],
       [9105, 8072, 4456, 4427,    0,    0,    0,    0]], dtype=int32)

In [44]:
# feature representation
dim = 10


In [45]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=max_length))
model.build(input_shape=(None,max_length))
model.compile('adam','mse')

In [46]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[[-4.7747977e-03,  9.8642111e-03, -2.7598513e-02, -4.1040469e-02,
          2.5237892e-02,  2.7368281e-02, -4.5569479e-02, -4.7407772e-02,
         -3.3633664e-02, -2.8714001e-02],
        [-4.0833019e-02, -4.0849376e-02, -6.7203417e-03, -3.6257483e-02,
          2.4625566e-02,  2.6725661e-02, -1.8748451e-02,  4.1956130e-02,
          1.5808653e-02, -2.1871496e-02],
        [ 3.4447957e-02,  1.7366480e-02, -3.1690516e-02, -3.1805359e-02,
         -4.2354014e-02, -4.9881469e-02, -2.6139189e-02,  1.6661771e-03,
         -3.1738535e-02,  3.2232713e-02],
        [ 4.3653671e-02,  9.0764835e-04, -3.7964821e-02, -4.8969872e-03,
          4.2907108e-02,  1.1049621e-03, -3.4080744e-03,  2.5087152e-02,
         -1.5383612e-02, -2.1183312e-02],
        [-2.4631429e-02,  4.0934570e-03, -2.7253866e-02, -4.9923684e-02,
          2.0146932e-02,  1.5730683e-02, -3.7421547e-02,  4.8369657e-02,
         -1.5736483e-02, -3.5538614e-02],
        [-2.4631429e-02,  4.0934570e-03, -2.7253866e-02, -4.

In [48]:
embedded_docs[0]

array([2608, 7686, 7767, 8406,    0,    0,    0,    0], dtype=int32)